#!/bin/sh
#
# PROVIDE: bsdpanel
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable bsdpanel:
# bsdpanel_enable="YES"

. /etc/rc.subr

name="bsdpanel"
rcvar="bsdpanel_enable"

load_rc_config $name

: ${bsdpanel_enable:="NO"}
: ${bsdpanel_user:="bsdpanel"}
: ${bsdpanel_group:="bsdpanel"}
: ${bsdpanel_config:="/usr/local/etc/bsdpanel.json"}

rundir="/var/run/${name}"
pidfile="${rundir}/${name}.pid"
procname="/usr/local/bin/bsdpanel"
command="/usr/sbin/daemon"
command_args="-c -f -p ${pidfile} -o /var/log/bsdpanel.log ${procname} -config ${bsdpanel_config}"

start_precmd="bsdpanel_prestart"

bsdpanel_prestart()
{
    # 1. Create PID runtime directory owned by daemon user
    install -d -o ${bsdpanel_user} -g ${bsdpanel_group} -m 0755 ${rundir}

    # 2. Create data storage directory owned by daemon user
    install -d -o ${bsdpanel_user} -g ${bsdpanel_group} -m 0750 /var/db/bsdpanel

    # 3. Create log file with correct ownership
    if [ ! -f /var/log/bsdpanel.log ]; then
        touch /var/log/bsdpanel.log
        chown ${bsdpanel_user}:${bsdpanel_group} /var/log/bsdpanel.log
        chmod 0640 /var/log/bsdpanel.log
    fi
}

run_rc_command "$1"
